/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';

export interface AssetSearchDTO {
  assetType?: AssetType;
  /** @nullable */
  searchTerm?: string | null;
}
