/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetDTO } from './assetDTO';

export interface AssetSearchResultDTO {
  assets: AssetDTO[];
}
