/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';
import type { MediaUpdateDTO } from './mediaUpdateDTO';

export interface AssetUpdateDTO {
  assetType?: AssetType;
  description?: string | null;
  id?: number;
  medias?: MediaUpdateDTO[] | null;
  name?: string | null;
}
