/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetInformationDTO } from './assetInformationDTO';
import type { ProjectInformationDTO } from './projectInformationDTO';

export interface AssetOfferDTO {
  asset?: AssetInformationDTO;
  assetUsageEndTime: string;
  assetUsageStartTime: string;
  description: string;
  duration: number;
  id: number;
  offerValue: number;
  project?: ProjectInformationDTO;
}
