/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';
import type { User } from './user';

export interface Asset {
  assetType?: AssetType;
  cost?: number;
  description?: string | null;
  fileSrcs?: string[] | null;
  id?: number;
  name?: string | null;
  uris?: string[] | null;
  user?: User;
  userId?: number;
}
