/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';
import type { UserInformationDTO } from './userInformationDTO';

export interface AssetInformationDTO {
  assetType: AssetType;
  /** @minLength 1 */
  description: string;
  id: number;
  /** @minLength 1 */
  name: string;
  owner: UserInformationDTO;
}
