/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface AssetOfferCreateDTO {
  assetId: number;
  assetUsageEndTime: string;
  assetUsageStartTime: string;
  description?: string | null;
  duration: number;
  offerValue: number;
  projectId: number;
}
