/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';
import type { MediaDTO } from './mediaDTO';

export interface AssetDTO {
  assetType: AssetType;
  description: string;
  id: number;
  medias: MediaDTO[];
  name: string;
}
