/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetOfferDTO } from './assetOfferDTO';

export interface AssetOfferDTOAPIResponse {
  data?: AssetOfferDTO;
  error?: string | null;
  success?: boolean;
}
