/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetSearchResultDTO } from './assetSearchResultDTO';

export interface AssetSearchResultDTOAPIResponse {
  data?: AssetSearchResultDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
