/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';
import type { MediaCreateDTO } from './mediaCreateDTO';

export interface AssetCreateDTO {
  assetType?: AssetType;
  description?: string | null;
  medias?: MediaCreateDTO[] | null;
  name?: string | null;
}
