/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetDTO } from './assetDTO';

export interface AssetDTOAPIResponse {
  data?: AssetDTO;
  error?: string | null;
  success?: boolean;
}
