/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';

export interface AssetSearchDTO {
  assetType?: AssetType;
  searchTerm?: string | null;
}
