/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface BooleanAPIResponse {
  data?: boolean;
  error?: string | null;
  success?: boolean;
}
