/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { Ordinates } from './ordinates';

export interface CoordinateSequenceFactory {
  ordinates?: Ordinates;
}
