/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface Coordinate {
  coordinateValue?: Coordinate;
  readonly isValid?: boolean;
  m?: number;
  x?: number;
  y?: number;
  z?: number;
}
