/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface CreateSurveyAnswerDTO {
  /** @nullable */
  answer?: string | null;
  questionId?: number;
  surveyId?: number;
  userId?: number;
}
