/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';

export interface EncryptedKeyExchangeDTO {
  chatType?: ChatType;
  encryptedSymmetricKey?: string | null;
  nonce?: string | null;
  publicKey?: string | null;
  senderId?: number;
  targetId?: number;
}
