/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface EncryptedKeyExchangeCreateDTO {
  /** @nullable */
  chatId?: string | null;
  /** @nullable */
  encryptedSymmetricKey?: string | null;
  /** @nullable */
  nonce?: string | null;
  /** @nullable */
  publicKey?: string | null;
  targetId?: number;
}
