/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';

export interface EncryptedKeyExchangeCreateDTO {
  chatType?: ChatType;
  /** @nullable */
  encryptedSymmetricKey?: string | null;
  /** @nullable */
  groupChatId?: number | null;
  /** @nullable */
  nonce?: string | null;
  /** @nullable */
  publicKey?: string | null;
  targetId?: number;
}
