/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';

export interface EncryptedKeyExchangeDTO {
  chatType: ChatType;
  /** @minLength 1 */
  encryptedSymmetricKey: string;
  /** @nullable */
  groupChatId?: number | null;
  id: string;
  /** @minLength 1 */
  nonce: string;
  /** @minLength 1 */
  publicKey: string;
  senderId: number;
  targetId: number;
}
