/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { EncryptedKeyExchangeDTO } from './encryptedKeyExchangeDTO';

export interface EncryptedKeyExchangeDTOAPIResponse {
  data?: EncryptedKeyExchangeDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
