/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface EnquiryCreateDTO {
  /** @nullable */
  enquiryMessage?: string | null;
  projectRoleId?: number;
}
