/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { EnquiryMessageDTO } from './enquiryMessageDTO';

export interface EnquiryMessageDTOAPIResponse {
  data?: EnquiryMessageDTO;
  error?: string | null;
  success?: boolean;
}
