/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { NewEnquiryMessageCreateDTO } from './newEnquiryMessageCreateDTO';

export interface EnquiryCreateDTO {
  message?: NewEnquiryMessageCreateDTO;
  projectRoleId?: number;
}
