/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaType } from './mediaType';

export interface EnquiryMessageDTO {
  date?: string;
  enquiryId?: number;
  id?: number;
  mediaType?: MediaType;
  message?: string | null;
  senderId?: number;
  uri?: string | null;
}
