/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserInformationDTO } from './userInformationDTO';

export interface EnquiryDTO {
  enquirer?: UserInformationDTO;
  /** @nullable */
  enquiryMessage?: string | null;
  id?: number;
  projectManager?: UserInformationDTO;
  projectRoleId?: number;
  shortlisted?: boolean;
}
