/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { EnquiryDTO } from './enquiryDTO';

export interface EnquiryDTOAPIResponse {
  data?: EnquiryDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
