/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserInformationDTO } from './userInformationDTO';
import type { EnquiryMessageDTO } from './enquiryMessageDTO';

export interface EnquiryDTO {
  enquirer?: UserInformationDTO;
  id?: number;
  messages?: EnquiryMessageDTO[] | null;
  projectManager?: UserInformationDTO;
  projectRoleId?: number;
}
