/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ExperienceType } from './experienceType';
import type { MediaDTO } from './mediaDTO';
import type { ProjectDTO } from './projectDTO';
import type { ProjectRoleDTO } from './projectRoleDTO';
import type { UserDTO } from './userDTO';

export interface ExperienceDTO {
  description: string;
  experienceType: ExperienceType;
  id: number;
  medias: MediaDTO[];
  project: ProjectDTO;
  projectId: number;
  projectRole: ProjectRoleDTO;
  projectRoleId: number;
  user: UserDTO;
  userId: number;
}
