/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ExperienceType } from './experienceType';
import type { MediaCreateDTO } from './mediaCreateDTO';

export interface ExperienceCreateDTO {
  description?: string | null;
  experienceId?: number;
  experienceType?: ExperienceType;
  medias?: MediaCreateDTO[] | null;
}
