/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { Dimension } from './dimension';
import type { Point } from './point';
import type { Coordinate } from './coordinate';
import type { Envelope } from './envelope';
import type { GeometryFactory } from './geometryFactory';
import type { OgcGeometryType } from './ogcGeometryType';
import type { PrecisionModel } from './precisionModel';
import type { GeometryUserData } from './geometryUserData';

export interface Geometry {
  readonly area?: number;
  boundary?: Geometry;
  boundaryDimension?: Dimension;
  centroid?: Point;
  coordinate?: Coordinate;
  /** @nullable */
  readonly coordinates?: readonly Coordinate[] | null;
  dimension?: Dimension;
  envelope?: Geometry;
  envelopeInternal?: Envelope;
  factory?: GeometryFactory;
  /** @nullable */
  readonly geometryType?: string | null;
  interiorPoint?: Point;
  readonly isEmpty?: boolean;
  readonly isRectangle?: boolean;
  readonly isSimple?: boolean;
  readonly isValid?: boolean;
  readonly length?: number;
  readonly numGeometries?: number;
  readonly numPoints?: number;
  ogcGeometryType?: OgcGeometryType;
  pointOnSurface?: Point;
  precisionModel?: PrecisionModel;
  srid?: number;
  /** @nullable */
  userData?: GeometryUserData;
}
