/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserDTO } from './userDTO';

export interface LoginResponseDTO {
  token: string;
  user: UserDTO;
}
