/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { LoginResponseDTO } from './loginResponseDTO';

export interface LoginResponseDTOAPIResponse {
  data?: LoginResponseDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
