/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaType } from './mediaType';

export interface MediaUpdateDTO {
  id?: number;
  mediaType?: MediaType;
  uri?: string | null;
}
