/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaType } from './mediaType';

export interface MediaDTO {
  id: number;
  mediaType: MediaType;
  /** @minLength 1 */
  uri: string;
}
