/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';
import type { MediaType } from './mediaType';

export interface MessageCreateDTO {
  chatType?: ChatType;
  /** @nullable */
  content?: string | null;
  date?: string;
  id?: string;
  mediaType?: MediaType;
  /** @nullable */
  replyMessageId?: string | null;
  targetId?: number;
  /** @nullable */
  uri?: string | null;
}
