/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MessageDTO } from './messageDTO';

export interface MessageDTOAPIResponse {
  data?: MessageDTO;
  error?: string | null;
  success?: boolean;
}
