/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';
import type { MediaType } from './mediaType';

export interface MessageCreateDTO {
  chatType?: ChatType;
  content?: string | null;
  date?: string;
  id?: string;
  mediaType?: MediaType;
  replyMessageId?: string | null;
  targetId?: number;
  uri?: string | null;
}
