/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';
import type { Emoji } from './emoji';

export interface MessageReactionCreateDTO {
  chatType?: ChatType;
  messageId?: string;
  multiplier?: number;
  reaction?: Emoji;
  targetId?: number;
}
