/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MessageReactionDTO } from './messageReactionDTO';

export interface MessageReactionDTOAPIResponse {
  data?: MessageReactionDTO;
  error?: string | null;
  success?: boolean;
}
