/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaUpdateDTO } from './mediaUpdateDTO';
import type { SkillType } from './skillType';

export interface PortofolioContentUpdateDTO {
  /** @nullable */
  description?: string | null;
  id?: number;
  /** @nullable */
  medias?: MediaUpdateDTO[] | null;
  /** @nullable */
  order?: number | null;
  skillType?: SkillType;
}
