/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { FileType } from './fileType';

export interface PortofolioContentDTO {
  description?: string | null;
  fileType?: FileType;
  id?: number;
  name?: string | null;
  order?: number;
  uri?: string | null;
}
