/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaCreateDTO } from './mediaCreateDTO';
import type { SkillType } from './skillType';

export interface PortofolioContentCreateDTO {
  /** @minLength 1 */
  description: string;
  medias: MediaCreateDTO[];
  order?: number;
  skillType: SkillType;
}
