/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaDTO } from './mediaDTO';
import type { SkillType } from './skillType';

export interface PortofolioContentDTO {
  /** @minLength 1 */
  description: string;
  id: number;
  medias: MediaDTO[];
  skillType: SkillType;
}
