/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { PortofolioContentDTO } from './portofolioContentDTO';

export interface PortofolioContentDTOAPIResponse {
  data?: PortofolioContentDTO;
  error?: string | null;
  success?: boolean;
}
