/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { PortofolioContentDTO } from './portofolioContentDTO';

export interface PortofolioContentDTOAPIResponse {
  data?: PortofolioContentDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
