/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export type PostApiProjectBody = {
  MediaFiles?: Blob[];
  'ProjectCreateDTO.Description'?: string;
  'ProjectCreateDTO.Name'?: string;
};
