/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';

export type PostApiAssetBody = {
  'Asset.AssetType'?: AssetType;
  'Asset.Cost'?: number;
  'Asset.Description'?: string;
  'Asset.Name'?: string;
  MediaFiles?: Blob[];
};
