/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { FileType } from './fileType';

export type PostApiPortofolioContentBody = {
  MediaFile?: Blob;
  'PortofolioContent.Description'?: string;
  'PortofolioContent.FileType'?: FileType;
  'PortofolioContent.Name'?: string;
  'PortofolioContent.Order'?: number;
};
