/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillType } from './skillType';

export type PostApiProjectRoleBody = {
  MediaFiles?: Blob[];
  'ProjectRoleCreateDTO.Cost'?: number;
  'ProjectRoleCreateDTO.Description'?: string;
  'ProjectRoleCreateDTO.Effort'?: number;
  'ProjectRoleCreateDTO.Latitude'?: number;
  'ProjectRoleCreateDTO.Longitude'?: number;
  'ProjectRoleCreateDTO.Name'?: string;
  'ProjectRoleCreateDTO.ProjectId'?: number;
  'ProjectRoleCreateDTO.Remote'?: boolean;
  'ProjectRoleCreateDTO.SkillType'?: SkillType;
};
