/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';

export type PostApiAssetParams = {
'Asset.Name'?: string;
'Asset.Description'?: string;
'Asset.AssetType'?: AssetType;
'Asset.Order'?: number;
'Asset.Cost'?: number;
};
