/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectRoleDTO } from './projectRoleDTO';

export interface ProjectRoleDTOAPIResponse {
  data?: ProjectRoleDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
