/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaCreateDTO } from './mediaCreateDTO';

export interface ProjectCreateDTO {
  description?: string | null;
  medias?: MediaCreateDTO[] | null;
  name?: string | null;
}
