/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectDTO } from './projectDTO';

export interface ProjectDTOAPIResponse {
  data?: ProjectDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
