/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetOfferDTO } from './assetOfferDTO';
import type { MediaDTO } from './mediaDTO';
import type { UserInformationDTO } from './userInformationDTO';
import type { ProjectRoleDTO } from './projectRoleDTO';

export interface ProjectDTO {
  assetOffers: AssetOfferDTO[];
  completed: boolean;
  /** @minLength 1 */
  description: string;
  id: number;
  medias: MediaDTO[];
  /** @minLength 1 */
  name: string;
  projectManager: UserInformationDTO;
  projectRoles: ProjectRoleDTO[];
}
