/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectWithMatchingRolesListDTO } from './projectWithMatchingRolesListDTO';

export interface ProjectWithMatchingRolesListDTOAPIResponse {
  data?: ProjectWithMatchingRolesListDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
