/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserInformationDTO } from './userInformationDTO';

export interface ProjectInformationDTO {
  id: number;
  /** @minLength 1 */
  name: string;
  projectManager: UserInformationDTO;
}
