/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserInformationDTO } from './userInformationDTO';
import type { SkillType } from './skillType';

export interface ProjectRoleDTO {
  assignee?: UserInformationDTO;
  cost?: number;
  description?: string | null;
  effort?: number;
  id?: number;
  latitude?: number;
  longitude?: number;
  name?: string | null;
  remote?: boolean;
  skillType?: SkillType;
  uris?: string[] | null;
}
