/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaCreateDTO } from './mediaCreateDTO';
import type { ReviewCreateDTO } from './reviewCreateDTO';

export interface ProjectRoleCompleteDTO {
  description?: string | null;
  id?: number;
  medias?: MediaCreateDTO[] | null;
  reviews?: ReviewCreateDTO[] | null;
}
