/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectWithMatchingRoleDTO } from './projectWithMatchingRoleDTO';

export interface ProjectWithMatchingRoleDTOListAPIResponse {
  data?: ProjectWithMatchingRoleDTO[] | null;
  error?: string | null;
  success?: boolean;
}
