/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaType } from './mediaType';
import type { ProjectRole } from './projectRole';

export interface ProjectRoleMedia {
  id?: number;
  mediaType?: MediaType;
  order?: number;
  projectRole?: ProjectRole;
  projectRoleId?: number;
  uri?: string | null;
}
