/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaCreateDTO } from './mediaCreateDTO';
import type { SkillType } from './skillType';

export interface ProjectRoleCreateDTO {
  address?: string | null;
  cost?: number;
  description?: string | null;
  effort?: number;
  endDate?: string;
  keywords?: string[] | null;
  latitude?: number;
  longitude?: number;
  medias?: MediaCreateDTO[] | null;
  name?: string | null;
  projectId?: number;
  remote?: boolean;
  skillType?: SkillType;
  startDate?: string;
}
