/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserInformationDTO } from './userInformationDTO';
import type { EnquiryDTO } from './enquiryDTO';
import type { MediaDTO } from './mediaDTO';
import type { SkillType } from './skillType';

export interface ProjectRoleDTO {
  address: string;
  assignee?: UserInformationDTO;
  completed?: boolean;
  cost: number;
  description: string;
  effort: number;
  endDate: string;
  enquiries?: EnquiryDTO[] | null;
  id: number;
  keywords: string[];
  latitude: number;
  longitude: number;
  medias?: MediaDTO[] | null;
  name: string;
  projectId: number;
  remote?: boolean;
  skillType: SkillType;
  startDate: string;
}
