/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectDTO } from './projectDTO';

export interface ProjectWithMatchingRoleDTO {
  project?: ProjectDTO;
  projectRoleId?: number;
}
