/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectCompletedDTO } from './projectCompletedDTO';

export interface ProjectCompletedDTOAPIResponse {
  data?: ProjectCompletedDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
