/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectWithMatchingRoleDTO } from './projectWithMatchingRoleDTO';

export interface ProjectWithMatchingRolesListDTO {
  projectWithMatchingRoles?: ProjectWithMatchingRoleDTO[] | null;
}
