/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaDTO } from './mediaDTO';
import type { UserInformationDTO } from './userInformationDTO';
import type { ProjectRoleDTO } from './projectRoleDTO';

export interface ProjectCompletedDTO {
  description: string;
  experiencesMedias: MediaDTO[];
  id: number;
  medias: MediaDTO[];
  name: string;
  projectManager: UserInformationDTO;
  projectRoles: ProjectRoleDTO[];
}
