/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';

export type PutApiAssetBody = {
  'AssetUpdateDTO.AssetType'?: AssetType;
  'AssetUpdateDTO.Cost'?: number;
  'AssetUpdateDTO.Description'?: string;
  'AssetUpdateDTO.FileSrcs'?: string[];
  'AssetUpdateDTO.Id'?: number;
  'AssetUpdateDTO.Name'?: string;
  MediaFiles?: Blob[];
};
