/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { FileType } from './fileType';

export type PutApiPortofolioContentParams = {
'PortofolioContentUpdateDTO.Id'?: number;
'PortofolioContentUpdateDTO.Description'?: string;
'PortofolioContentUpdateDTO.Name'?: string;
'PortofolioContentUpdateDTO.FileType'?: FileType;
'PortofolioContentUpdateDTO.Order'?: number;
};
