/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { FileType } from './fileType';

export type PutApiPortofolioContentBody = {
  MediaFile?: Blob;
  'PortofolioContentUpdateDTO.Description'?: string;
  'PortofolioContentUpdateDTO.FileType'?: FileType;
  'PortofolioContentUpdateDTO.Id'?: number;
  'PortofolioContentUpdateDTO.Name'?: string;
  'PortofolioContentUpdateDTO.Order'?: number;
};
