/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';

export type PutApiAssetParams = {
'AssetUpdateDTO.Id'?: number;
'AssetUpdateDTO.Name'?: string;
'AssetUpdateDTO.Description'?: string;
'AssetUpdateDTO.AssetType'?: AssetType;
'AssetUpdateDTO.Cost'?: number;
'AssetUpdateDTO.FileSrcs'?: string[];
};
