/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { RedeemVoucherCodeResponseDTO } from './redeemVoucherCodeResponseDTO';

export interface RedeemVoucherCodeResponseDTOAPIResponse {
  data?: RedeemVoucherCodeResponseDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
