/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserInformationDTO } from './userInformationDTO';

export interface ReviewDTO {
  createdAt?: string;
  description?: string | null;
  rating?: number;
  reviewerUser?: UserInformationDTO;
}
