/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface ReviewCreateDTO {
  description?: string | null;
  rating?: number;
  reviewedUserId?: number;
}
