/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SeenMatchesDTO } from './seenMatchesDTO';

export interface SeenMatchesDTOAPIResponse {
  data?: SeenMatchesDTO;
  error?: string | null;
  success?: boolean;
}
