/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillGroupType } from './skillGroupType';
import type { SkillType } from './skillType';

export interface SkillUpdateDTO {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  id?: number | null;
  /** @nullable */
  keywords?: string[] | null;
  level?: number;
  skillGroupType?: SkillGroupType;
  skillType?: SkillType;
}
