/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillGroupType } from './skillGroupType';
import type { SkillType } from './skillType';

export interface SkillDTO {
  description?: string | null;
  id?: number;
  keywords?: string[] | null;
  level?: number;
  skillGroupType?: SkillGroupType;
  skillType?: SkillType;
}
