/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export type SkillGroupType = typeof SkillGroupType[keyof typeof SkillGroupType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SkillGroupType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
