/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export type SkillGroupType = typeof SkillGroupType[keyof typeof SkillGroupType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SkillGroupType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
} as const;
