/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SurveyAnswerListDTO } from './surveyAnswerListDTO';

export interface SurveyAnswerListDTOAPIResponse {
  data?: SurveyAnswerListDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
