/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserLoginDTO {
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  username: string;
}
