/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserInformationDTO {
  /** @nullable */
  publicKey?: string | null;
  /** @nullable */
  rating?: number | null;
  userId: number;
  /** @minLength 1 */
  username: string;
}
