/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserProfileDTO } from './userProfileDTO';

export interface UserProfileDTOAPIResponse {
  data?: UserProfileDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
