/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserPortofolioDTO } from './userPortofolioDTO';

export interface UserPortofolioDTOAPIResponse {
  data?: UserPortofolioDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
