/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserLoginResponseDTO {
  /** @minLength 1 */
  bannerPictureSrc: string;
  /** @minLength 1 */
  email: string;
  userId: number;
  /** @minLength 1 */
  username: string;
}
