/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserLocationDTO } from './userLocationDTO';

export interface UserLocationDTOAPIResponse {
  data?: UserLocationDTO;
  error?: string | null;
  success?: boolean;
}
