/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserChangePasswordDTO {
  /** @minLength 1 */
  newPassword: string;
  /** @minLength 1 */
  oldPassword: string;
}
