/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { Asset } from './asset';
import type { PortofolioContent } from './portofolioContent';
import type { Review } from './review';
import type { Skill } from './skill';

export interface User {
  aboutYou?: string | null;
  assets?: Asset[] | null;
  bannerPictureSrc?: string | null;
  coins?: number;
  email?: string | null;
  location?: string | null;
  password?: string | null;
  portofolioContents?: PortofolioContent[] | null;
  profilePictureSrc?: string | null;
  rating?: number;
  reviewsGiven?: Review[] | null;
  reviewsReceived?: Review[] | null;
  skills?: Skill[] | null;
  totalReviews?: number;
  userId?: number;
  username?: string | null;
}
