/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserProfileDTO } from './userProfileDTO';

export interface UserProfilesDTO {
  userProfiles?: UserProfileDTO[] | null;
}
