/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserCreateDTO {
  email?: string | null;
  location?: string | null;
  password?: string | null;
  username?: string | null;
}
