/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillUpdateDTO } from './skillUpdateDTO';

export interface UserUpdateDTO {
  aboutYou?: string | null;
  email?: string | null;
  skills?: SkillUpdateDTO[] | null;
  username?: string | null;
}
