/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { PortofolioContentDTO } from './portofolioContentDTO';

export interface UserPortofolioDTO {
  aboutYou?: string | null;
  portofolioContents?: PortofolioContentDTO[] | null;
}
