/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserProfilesDTO } from './userProfilesDTO';

export interface UserProfilesDTOAPIResponse {
  data?: UserProfilesDTO;
  error?: string | null;
  success?: boolean;
}
