/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserDTO } from './userDTO';

export interface UserDTOAPIResponse {
  data?: UserDTO;
  /** @nullable */
  error?: string | null;
  success?: boolean;
}
