/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ExperienceDTO } from './experienceDTO';
import type { PortofolioContentDTO } from './portofolioContentDTO';
import type { ReviewDTO } from './reviewDTO';
import type { SkillDTO } from './skillDTO';

export interface UserProfileDTO {
  /** @minLength 1 */
  aboutYou: string;
  experiences: ExperienceDTO[];
  portofolioContents: PortofolioContentDTO[];
  rating: number;
  reviewsReceived: ReviewDTO[];
  skills: SkillDTO[];
  totalReviews: number;
  userId: number;
  /** @minLength 1 */
  username: string;
}
