/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserInformationDTO {
  publicKey?: string | null;
  userId: number;
  username: string;
}
