/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { PortofolioContentDTO } from './portofolioContentDTO';
import type { SkillDTO } from './skillDTO';

export interface UserProfileDTO {
  aboutYou?: string | null;
  portofolioContents?: PortofolioContentDTO[] | null;
  rating?: number;
  skills?: SkillDTO[] | null;
  totalReviews?: number;
  userId?: number;
  username?: string | null;
}
