/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserPortofolioDTO } from './userPortofolioDTO';

export interface UserPortofolioDTOListAPIResponse {
  data?: UserPortofolioDTO[] | null;
  error?: string | null;
  success?: boolean;
}
