import { SkillGroups } from "./skillGroup";
import { Skills } from "./skills";

export const skillGroupMap = {
  [Skills.Editor]: SkillGroups.Filmmaking,
  [Skills.Director]: SkillGroups.Filmmaking,
  [Skills.Producer]: SkillGroups.Filmmaking,
  [Skills.Screenwriter]: SkillGroups.Filmmaking,
  [Skills.Cinematographer]: SkillGroups.Filmmaking,
  [Skills.SoundDesigner]: SkillGroups.Filmmaking,
  [Skills.ProductionDesigner]: SkillGroups.Filmmaking,
  [Skills.SpecialEffects]: SkillGroups.Filmmaking,
  [Skills.ScriptSupervisor]: SkillGroups.Filmmaking,
  [Skills.CastingDirector]: SkillGroups.Filmmaking,
  [Skills.MakeupArtist]: SkillGroups.Filmmaking,
  [Skills.CostumeDesigner]: SkillGroups.Filmmaking,
  [Skills.BoomOperator]: SkillGroups.Filmmaking,
  [Skills.PropsManager]: SkillGroups.Filmmaking,
  [Skills.SoundMixer]: SkillGroups.Filmmaking,
  [Skills.Runner]: SkillGroups.Filmmaking,
  [Skills.ProductionAssistant]: SkillGroups.Filmmaking,
  [Skills.Chreographer]: SkillGroups.Filmmaking,
  [Skills.AssistantDirector]: SkillGroups.Filmmaking,
  [Skills.CoProducer]: SkillGroups.Filmmaking,
  [Skills.HairStylist]: SkillGroups.Filmmaking,
  [Skills.Grip]: SkillGroups.Filmmaking,
  [Skills.LocationManager]: SkillGroups.Filmmaking,
  [Skills.SetDresser]: SkillGroups.Filmmaking,
  [Skills.StoryBoardArtist]: SkillGroups.Filmmaking,
  [Skills.Animator]: SkillGroups.Filmmaking,
  [Skills.LeadActorScreen]: SkillGroups.Acting,
  [Skills.LeasAcressScreen]: SkillGroups.Acting,
  [Skills.Extra]: SkillGroups.Acting,
  [Skills.SupportingActorScreen]: SkillGroups.Acting,
  [Skills.SupportingActressScreen]: SkillGroups.Acting,
  [Skills.BackgroundActorActress]: SkillGroups.Acting,
  [Skills.VoiceActorActress]: SkillGroups.Acting,
  [Skills.StandIn]: SkillGroups.Acting,
  [Skills.Dancer]: SkillGroups.Acting,
  [Skills.LeadActorTheatre]: SkillGroups.Acting,
  [Skills.LeadActressTheatre]: SkillGroups.Acting,
  [Skills.MusicalTheatrePerformer]: SkillGroups.Acting,
  [Skills.SupportingActorTheatre]: SkillGroups.Acting,
  [Skills.SupportingActressTheatre]: SkillGroups.Acting,
  [Skills.ActorModel]: SkillGroups.Acting,
};
