import { Skills } from "./skills";

export const skillsToIconMapping: { [key in Skills]: string } = {
  [Skills.Editor]: "scissors",
  [Skills.Director]: "bullhorn",
  [Skills.Producer]: "list-check",
  [Skills.Screenwriter]: "quote-right",
  [Skills.Cinematographer]: "video",
  [Skills.SoundDesigner]: "file-audio",
  [Skills.ProductionDesigner]: "pencil",
  [Skills.SpecialEffects]: "burst",
  [Skills.ScriptSupervisor]: "book",
  [Skills.CastingDirector]: "person-chalkboard",
  [Skills.MakeupArtist]: "paintbrush",
  [Skills.CostumeDesigner]: "shirt",
  [Skills.BoomOperator]: "microphone-lines",
  [Skills.PropsManager]: "glasses",
  [Skills.SoundMixer]: "sliders",
  [Skills.Runner]: "handshake-angle",
  [Skills.ProductionAssistant]: "clipboard-list",
  [Skills.Chreographer]: "arrow-right-arrow-left",
  [Skills.AssistantDirector]: "bullhorn",
  [Skills.CoProducer]: "list-check",
  [Skills.HairStylist]: "person-rays",
  [Skills.Grip]: "camera-rotate",
  [Skills.LocationManager]: "location-dot",
  [Skills.SetDresser]: "house",
  [Skills.StoryBoardArtist]: "users-viewfinder",
  [Skills.Animator]: "palette",
  [Skills.LeadActorScreen]: "person-rays",
  [Skills.LeasAcressScreen]: "person-rays",
  [Skills.Extra]: "people-group",
  [Skills.SupportingActorScreen]: "person",
  [Skills.SupportingActressScreen]: "person",
  [Skills.BackgroundActorActress]: "person-half-dress",
  [Skills.VoiceActorActress]: "microphone-lines",
  [Skills.StandIn]: "person-circle-plus",
  [Skills.Dancer]: "person-walking",
  [Skills.LeadActorTheatre]: "person-rays",
  [Skills.LeadActressTheatre]: "person-rays",
  [Skills.MusicalTheatrePerformer]: "guitar",
  [Skills.SupportingActorTheatre]: "person",
  [Skills.SupportingActressTheatre]: "person",
  [Skills.ActorModel]: "star"
};
