import { Skills } from "./skills";

export const skillsToStringMapping: { [index: number]: string } = {
  [Skills.Editor]: "Editor",
  [Skills.Director]: "Director",
  [Skills.Producer]: "Producer",
  [Skills.Screenwriter]: "Screenwriter",
  [Skills.Cinematographer]: "Cinematographer",
  [Skills.SoundDesigner]: "Sound Designer",
  [Skills.ProductionDesigner]: "Production Designer",
  [Skills.SpecialEffects]: "Special Effects",
  [Skills.ScriptSupervisor]: "Script Supervisor",
  [Skills.CastingDirector]: "Casting Director",
  [Skills.MakeupArtist]: "Makeup Artist",
  [Skills.CostumeDesigner]: "Costume Designer",
  [Skills.BoomOperator]: "Boom Operator",
  [Skills.PropsManager]: "Props Manager",
  [Skills.SoundMixer]: "Sound Mixer",
  [Skills.Runner]: "Runner",
  [Skills.ProductionAssistant]: "Production Assistant",
  [Skills.Chreographer]: "Chreographer",
  [Skills.AssistantDirector]: "Assistant Director",
  [Skills.CoProducer]: "Co-Producer",
  [Skills.HairStylist]: "Hair Stylist",
  [Skills.Grip]: "Grip",
  [Skills.LocationManager]: "Location Manager",
  [Skills.SetDresser]: "Set Dresser",
  [Skills.StoryBoardArtist]: "Story Board Artist",
  [Skills.Animator]: "Animator",
  [Skills.LeadActorScreen]: "Lead Actor (Screen)",
  [Skills.LeasAcressScreen]: "Lead Actress (Screen)",
  [Skills.Extra]: "Extra",
  [Skills.SupportingActorScreen]: "Supporting Actor (Screen)",
  [Skills.SupportingActressScreen]: "Supporting Actress (Screen)",
  [Skills.BackgroundActorActress]: "Background Actor/Actress",
  [Skills.VoiceActorActress]: "Voice Actor/Actress",
  [Skills.StandIn]: "Stand-In",
  [Skills.Dancer]: "Dancer",
  [Skills.LeadActorTheatre]: "Lead Actor (Theatre)",
  [Skills.LeadActressTheatre]: "Lead Actress (Theatre)",
  [Skills.MusicalTheatrePerformer]: "Musical Theatre Performer",
  [Skills.SupportingActorTheatre]: "Supporting Actor (Theatre)",
  [Skills.SupportingActressTheatre]: "Supporting Actress (Theatre)",
  [Skills.ActorModel]: "Actor/Model",
};
