/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  LoginRequest,
  LoginResponse,
  RegisterRequest
} from '../model'
import { customInstance } from '../../api/mutator/custom-instance';
import type { ErrorType } from '../../api/mutator/custom-instance';



export const postApiAuthenticationLogin = (
    loginRequest: LoginRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LoginResponse>(
      {url: `/api/authentication/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      );
    }
  


export const getPostApiAuthenticationLoginMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthenticationLogin>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthenticationLogin>>, TError,{data: LoginRequest}, TContext> => {
    
const mutationKey = ['postApiAuthenticationLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthenticationLogin>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthenticationLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthenticationLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthenticationLogin>>>
    export type PostApiAuthenticationLoginMutationBody = LoginRequest
    export type PostApiAuthenticationLoginMutationError = ErrorType<unknown>

    export const usePostApiAuthenticationLogin = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthenticationLogin>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthenticationLogin>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getPostApiAuthenticationLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const postApiAuthenticationRegister = (
    registerRequest: RegisterRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/authentication/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
      );
    }
  


export const getPostApiAuthenticationRegisterMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthenticationRegister>>, TError,{data: RegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthenticationRegister>>, TError,{data: RegisterRequest}, TContext> => {
    
const mutationKey = ['postApiAuthenticationRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthenticationRegister>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthenticationRegister(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthenticationRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthenticationRegister>>>
    export type PostApiAuthenticationRegisterMutationBody = RegisterRequest
    export type PostApiAuthenticationRegisterMutationError = ErrorType<unknown>

    export const usePostApiAuthenticationRegister = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthenticationRegister>>, TError,{data: RegisterRequest}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthenticationRegister>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {

      const mutationOptions = getPostApiAuthenticationRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const postApiAuthenticationToken = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/authentication/token`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiAuthenticationTokenMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthenticationToken>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthenticationToken>>, TError,void, TContext> => {
    
const mutationKey = ['postApiAuthenticationToken'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthenticationToken>>, void> = () => {
          

          return  postApiAuthenticationToken()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthenticationTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthenticationToken>>>
    
    export type PostApiAuthenticationTokenMutationError = ErrorType<unknown>

    export const usePostApiAuthenticationToken = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthenticationToken>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthenticationToken>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiAuthenticationTokenMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
