/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'


export const postApiAuthenticationLoginBody = zod.object({
  "usernameOrEmail": zod.string(),
  "password": zod.string()
})

export const postApiAuthenticationLoginResponse = zod.object({
  "token": zod.string(),
  "user": zod.object({
  "userId": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "coins": zod.number()
})
})


export const postApiAuthenticationRegisterBody = zod.object({
  "username": zod.string(),
  "email": zod.string(),
  "password": zod.string()
})


