/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AuthenticatedUser {
  userId: number;
  username: string;
  email: string;
  coins: number;
}
