/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticatedUser } from './authenticatedUser';

export interface LoginResponse {
  token: string;
  user: AuthenticatedUser;
}
