/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  username: string;
  email: string;
  password: string;
}
