/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface AssetOfferCreateDTO {
  offerValue: number;
  assetUsageStartTime: string;
  assetUsageEndTime: string;
  duration: number;
  /** @nullable */
  description?: string | null;
  assetId: number;
  projectId: number;
}
