/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetInformationDTO } from './assetInformationDTO';
import type { ProjectInformationDTO } from './projectInformationDTO';

export interface AssetOfferDTO {
  id: number;
  offerValue: number;
  assetUsageStartTime: string;
  assetUsageEndTime: string;
  duration: number;
  /** @minLength 1 */
  description: string;
  asset?: AssetInformationDTO;
  project?: ProjectInformationDTO;
}
