/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';
import type { MediaDTO } from './mediaDTO';

export interface AssetDTO {
  id: number;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  assetType: AssetType;
  medias: MediaDTO[];
}
