/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';

export interface AssetSearchDTO {
  /** @nullable */
  searchTerm?: string | null;
  assetType?: AssetType;
}
