/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';
import type { MediaUpdateDTO } from './mediaUpdateDTO';

export interface AssetUpdateDTO {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  assetType?: AssetType;
  /** @nullable */
  medias?: MediaUpdateDTO[] | null;
}
