/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetType } from './assetType';
import type { MediaCreateDTO } from './mediaCreateDTO';

export interface AssetCreateDTO {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  assetType?: AssetType;
  /** @nullable */
  medias?: MediaCreateDTO[] | null;
}
