/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetDTO } from './assetDTO';

export interface AssetDTOAPIResponse {
  success?: boolean;
  data?: AssetDTO;
  /** @nullable */
  error?: string | null;
}
