/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetSearchResultDTO } from './assetSearchResultDTO';

export interface AssetSearchResultDTOAPIResponse {
  success?: boolean;
  data?: AssetSearchResultDTO;
  /** @nullable */
  error?: string | null;
}
