/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { AssetOfferDTO } from './assetOfferDTO';

export interface AssetOfferDTOAPIResponse {
  success?: boolean;
  data?: AssetOfferDTO;
  /** @nullable */
  error?: string | null;
}
