/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';
import type { ChatMemberDTO } from './chatMemberDTO';

export interface ChatDTO {
  chatType: ChatType;
  chatTypeId: number;
  /** @minLength 1 */
  chatName: string;
  chatMembers: ChatMemberDTO[];
}
