/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface ChatMemberDTO {
  userId: number;
  /** @minLength 1 */
  userName: string;
  /** @minLength 1 */
  publicKey: string;
  /** @minLength 1 */
  profilePicture: string;
}
