/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';
import type { ChatMemberDTO } from './chatMemberDTO';

export interface ChatDTO {
  id: number;
  chatType: ChatType;
  chatTypeId: number;
  /** @minLength 1 */
  groupChatName: string;
  chatMembers: ChatMemberDTO[];
}
