/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { Coordinate } from './coordinate';
import type { Ordinates } from './ordinates';

export interface CoordinateSequence {
  readonly count?: number;
  readonly dimension?: number;
  first?: Coordinate;
  readonly hasM?: boolean;
  readonly hasZ?: boolean;
  last?: Coordinate;
  readonly measures?: number;
  readonly mOrdinateIndex?: number;
  ordinates?: Ordinates;
  readonly spatial?: number;
  readonly zOrdinateIndex?: number;
}
