/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface Coordinate {
  x?: number;
  y?: number;
  z?: number;
  m?: number;
  coordinateValue?: Coordinate;
  readonly isValid?: boolean;
}
