/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface CreateSurveyAnswerDTO {
  userId?: number;
  surveyId?: number;
  questionId?: number;
  /** @nullable */
  answer?: string | null;
}
