/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { CreateSurveyAnswerDTO } from './createSurveyAnswerDTO';

export interface CreateSurveyAnswerListDTO {
  /** @nullable */
  surveyAnswers?: CreateSurveyAnswerDTO[] | null;
}
