/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export type Emoji = typeof Emoji[keyof typeof Emoji];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Emoji = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
