/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { EncryptedKeyExchangeDTO } from './encryptedKeyExchangeDTO';

export interface EncryptedKeyExchangeDTOAPIResponse {
  success?: boolean;
  data?: EncryptedKeyExchangeDTO;
  /** @nullable */
  error?: string | null;
}
