/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';

export interface EncryptedKeyExchangeCreateDTO {
  /** @minLength 1 */
  nonce: string;
  /** @minLength 1 */
  publicKey: string;
  /** @minLength 1 */
  encryptedSymmetricKey: string;
  targetId: number;
  chatType: ChatType;
  /** @minLength 1 */
  chatId: string;
}
