/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface EncryptedKeyExchangeCreateDTO {
  /** @nullable */
  nonce?: string | null;
  /** @nullable */
  publicKey?: string | null;
  /** @nullable */
  encryptedSymmetricKey?: string | null;
  targetId?: number;
  /** @nullable */
  chatId?: string | null;
}
