/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface EncryptedKeyExchangeDTO {
  id: string;
  /** @minLength 1 */
  nonce: string;
  /** @minLength 1 */
  publicKey: string;
  /** @minLength 1 */
  encryptedSymmetricKey: string;
  chatId: number;
}
