/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserInformationDTO } from './userInformationDTO';

export interface EnquiryDTO {
  id: number;
  projectRoleId: number;
  enquirer?: UserInformationDTO;
  projectManager?: UserInformationDTO;
  /** @nullable */
  projectId?: number | null;
  /** @minLength 1 */
  enquiryMessage: string;
  shortlisted: boolean;
}
