/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { EnquiryDTO } from './enquiryDTO';

export interface EnquiryDTOAPIResponse {
  success?: boolean;
  data?: EnquiryDTO;
  /** @nullable */
  error?: string | null;
}
