/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { Coordinate } from './coordinate';

export interface Envelope {
  readonly isNull?: boolean;
  readonly width?: number;
  readonly height?: number;
  readonly diameter?: number;
  readonly minX?: number;
  readonly maxX?: number;
  readonly minY?: number;
  readonly maxY?: number;
  readonly area?: number;
  readonly minExtent?: number;
  readonly maxExtent?: number;
  centre?: Coordinate;
}
