/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserDTO } from './userDTO';
import type { MediaDTO } from './mediaDTO';
import type { ExperienceType } from './experienceType';
import type { ProjectRoleDTO } from './projectRoleDTO';
import type { ProjectDTO } from './projectDTO';

export interface ExperienceDTO {
  id: number;
  /** @minLength 1 */
  description: string;
  userId: number;
  user: UserDTO;
  medias: MediaDTO[];
  experienceType: ExperienceType;
  projectRoleId: number;
  projectRole: ProjectRoleDTO;
  projectId: number;
  project: ProjectDTO;
}
