/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaCreateDTO } from './mediaCreateDTO';
import type { ExperienceType } from './experienceType';

export interface ExperienceCreateDTO {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  medias?: MediaCreateDTO[] | null;
  experienceType?: ExperienceType;
  experienceId?: number;
}
