/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export type ExperienceType = typeof ExperienceType[keyof typeof ExperienceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExperienceType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
