/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { PrecisionModel } from './precisionModel';
import type { CoordinateSequenceFactory } from './coordinateSequenceFactory';
import type { NtsGeometryServices } from './ntsGeometryServices';

export interface GeometryFactory {
  precisionModel?: PrecisionModel;
  coordinateSequenceFactory?: CoordinateSequenceFactory;
  readonly srid?: number;
  geometryServices?: NtsGeometryServices;
}
