/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface LocationDTO {
  longitude: number;
  latitude: number;
  /** @minLength 1 */
  address: string;
}
