/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { LoginResponseDTO } from './loginResponseDTO';

export interface LoginResponseDTOAPIResponse {
  success?: boolean;
  data?: LoginResponseDTO;
  /** @nullable */
  error?: string | null;
}
