/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserLoginResponseDTO } from './userLoginResponseDTO';

export interface LoginResponseDTO {
  /** @minLength 1 */
  token: string;
  user: UserLoginResponseDTO;
}
