/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserDTO } from './userDTO';

export interface LoginResponseDTO {
  /** @minLength 1 */
  token: string;
  user: UserDTO;
}
