/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaType } from './mediaType';

export interface MediaDTO {
  id: number;
  /** @minLength 1 */
  uri: string;
  mediaType: MediaType;
}
