/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaType } from './mediaType';

export interface MediaCreateDTO {
  /** @minLength 1 */
  uri: string;
  mediaType: MediaType;
}
