/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaType } from './mediaType';

export interface MediaUpdateDTO {
  id?: number;
  /** @nullable */
  uri?: string | null;
  mediaType?: MediaType;
}
