/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MessageReactionDTO } from './messageReactionDTO';

export interface MessageReactionDTOAPIResponse {
  success?: boolean;
  data?: MessageReactionDTO;
  /** @nullable */
  error?: string | null;
}
