/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { Emoji } from './emoji';
import type { ChatType } from './chatType';

export interface MessageReactionCreateDTO {
  messageId?: string;
  multiplier?: number;
  reaction?: Emoji;
  targetId?: number;
  chatType?: ChatType;
  /** @nullable */
  chatId?: string | null;
}
