/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MessageDTO } from './messageDTO';

export interface MessageDTOAPIResponse {
  success?: boolean;
  data?: MessageDTO;
  /** @nullable */
  error?: string | null;
}
