/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { Emoji } from './emoji';

export interface MessageReactionDTO {
  messageId: string;
  userId: number;
  multiplier: number;
  reaction: Emoji;
}
