/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface MessageDTO {
  id?: string;
  /** @nullable */
  salt?: string | null;
  chatId?: number;
  senderId?: number;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  uri?: string | null;
  date?: string;
  /** @nullable */
  replyMessageId?: string | null;
}
