/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface MessageCreateDTO {
  id: string;
  /** @minLength 1 */
  salt: string;
  chatId: number;
  targetUserIds: number[];
  /** @nullable */
  content?: string | null;
  /** @nullable */
  uri?: string | null;
  date: string;
  /** @nullable */
  replyMessageId?: string | null;
}
