/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ChatType } from './chatType';
import type { MediaType } from './mediaType';

export interface MessageDTO {
  id: string;
  senderId: number;
  targetId: number;
  chatType: ChatType;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  uri?: string | null;
  mediaType?: MediaType;
  date: string;
  /** @nullable */
  replyMessageId?: string | null;
  /** @minLength 1 */
  chatId: string;
}
