/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { GeometryOverlay } from './geometryOverlay';
import type { CoordinateEqualityComparer } from './coordinateEqualityComparer';
import type { CoordinateSequenceFactory } from './coordinateSequenceFactory';
import type { PrecisionModel } from './precisionModel';

export interface NtsGeometryServices {
  geometryOverlay?: GeometryOverlay;
  coordinateEqualityComparer?: CoordinateEqualityComparer;
  readonly defaultSRID?: number;
  defaultCoordinateSequenceFactory?: CoordinateSequenceFactory;
  defaultPrecisionModel?: PrecisionModel;
}
