/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { CoordinateEqualityComparer } from './coordinateEqualityComparer';
import type { CoordinateSequenceFactory } from './coordinateSequenceFactory';
import type { PrecisionModel } from './precisionModel';
import type { GeometryOverlay } from './geometryOverlay';

export interface NtsGeometryServices {
  coordinateEqualityComparer?: CoordinateEqualityComparer;
  defaultCoordinateSequenceFactory?: CoordinateSequenceFactory;
  defaultPrecisionModel?: PrecisionModel;
  readonly defaultSRID?: number;
  geometryOverlay?: GeometryOverlay;
}
