/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { PortofolioContentDTO } from './portofolioContentDTO';

export interface PortofolioContentDTOAPIResponse {
  success?: boolean;
  data?: PortofolioContentDTO;
  /** @nullable */
  error?: string | null;
}
