/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillType } from './skillType';
import type { MediaDTO } from './mediaDTO';

export interface PortofolioContentDTO {
  id?: number;
  /** @nullable */
  description?: string | null;
  skillType?: SkillType;
  /** @nullable */
  medias?: MediaDTO[] | null;
}
