/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { PortofolioContentUpdateDTO } from './portofolioContentUpdateDTO';

export interface PortofolioContentGroupUpdateDTO {
  /** @nullable */
  portofolioContents?: PortofolioContentUpdateDTO[] | null;
}
