/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { PortofolioContentMedia } from './portofolioContentMedia';
import type { SkillType } from './skillType';
import type { User } from './user';

export interface PortofolioContent {
  createdAt?: string;
  description?: string | null;
  id?: number;
  medias?: PortofolioContentMedia[] | null;
  order?: number;
  skillType?: SkillType;
  user?: User;
  userId?: number;
}
