/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillType } from './skillType';
import type { MediaCreateDTO } from './mediaCreateDTO';

export interface PortofolioContentCreateDTO {
  /** @minLength 1 */
  description: string;
  order?: number;
  skillType: SkillType;
  medias: MediaCreateDTO[];
}
