/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillType } from './skillType';
import type { MediaUpdateDTO } from './mediaUpdateDTO';

export interface PortofolioContentUpdateDTO {
  id?: number;
  /** @nullable */
  description?: string | null;
  skillType?: SkillType;
  /** @nullable */
  order?: number | null;
  /** @nullable */
  medias?: MediaUpdateDTO[] | null;
}
