/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { EntityType } from './entityType';
import type { MediaType } from './mediaType';

export interface PrepareUploadDTO {
  entity?: EntityType;
  mediaType?: MediaType;
}
