/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectCompletedDTO } from './projectCompletedDTO';

export interface ProjectCompletedDTOAPIResponse {
  success?: boolean;
  data?: ProjectCompletedDTO;
  /** @nullable */
  error?: string | null;
}
