/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectDTO } from './projectDTO';

export interface ProjectDTOAPIResponse {
  success?: boolean;
  data?: ProjectDTO;
  /** @nullable */
  error?: string | null;
}
