/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { LocationDTO } from './locationDTO';
import type { MediaCreateDTO } from './mediaCreateDTO';
import type { ProjectRoleCreateDTO } from './projectRoleCreateDTO';

export interface ProjectCreateDTO {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  date: string;
  location: LocationDTO;
  medias: MediaCreateDTO[];
  projectRoles: ProjectRoleCreateDTO[];
}
