/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaDTO } from './mediaDTO';
import type { UserInformationDTO } from './userInformationDTO';
import type { ProjectRoleDTO } from './projectRoleDTO';

export interface ProjectCompletedDTO {
  id: number;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  medias: MediaDTO[];
  experiencesMedias: MediaDTO[];
  projectManager: UserInformationDTO;
  projectRoles: ProjectRoleDTO[];
}
