/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaCreateDTO } from './mediaCreateDTO';
import type { ProjectRoleCreateDTO } from './projectRoleCreateDTO';

export interface ProjectCreateDTO {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  date: string;
  longitude: number;
  latitude: number;
  /** @minLength 1 */
  address: string;
  medias: MediaCreateDTO[];
  projectRoles: ProjectRoleCreateDTO[];
}
