/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectRoleDTO } from './projectRoleDTO';

export interface ProjectRoleDTOAPIResponse {
  success?: boolean;
  data?: ProjectRoleDTO;
  /** @nullable */
  error?: string | null;
}
