/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaCreateDTO } from './mediaCreateDTO';

export interface ProjectCreateDTO {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  medias: MediaCreateDTO[];
}
