/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectWithMatchingRoleDTO } from './projectWithMatchingRoleDTO';

export interface ProjectWithMatchingRolesListDTO {
  projectWithMatchingRoles: ProjectWithMatchingRoleDTO[];
}
