/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillType } from './skillType';
import type { MediaCreateDTO } from './mediaCreateDTO';

export interface ProjectRoleCreateDTO {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  cost?: number;
  effort?: number;
  startDate?: string;
  endDate?: string;
  skillType?: SkillType;
  longitude?: number;
  latitude?: number;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  keywords?: string[] | null;
  remote?: boolean;
  projectId?: number;
  /** @nullable */
  medias?: MediaCreateDTO[] | null;
}
