/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillType } from './skillType';
import type { UserInformationDTO } from './userInformationDTO';
import type { MediaDTO } from './mediaDTO';
import type { EnquiryDTO } from './enquiryDTO';

export interface ProjectRoleDTO {
  id: number;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  cost: number;
  effort: number;
  skillType: SkillType;
  longitude: number;
  latitude: number;
  /** @minLength 1 */
  address: string;
  projectId: number;
  keywords: string[];
  remote?: boolean;
  completed?: boolean;
  assignee?: UserInformationDTO;
  medias: MediaDTO[];
  /** @nullable */
  enquiries?: EnquiryDTO[] | null;
}
