/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectMedia } from './projectMedia';
import type { User } from './user';
import type { ProjectRole } from './projectRole';

export interface Project {
  description?: string | null;
  id?: number;
  medias?: ProjectMedia[] | null;
  name?: string | null;
  projectManager?: User;
  projectManagerId?: number;
  projectRoles?: ProjectRole[] | null;
}
