/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { MediaDTO } from './mediaDTO';
import type { UserInformationDTO } from './userInformationDTO';
import type { ProjectRoleDTO } from './projectRoleDTO';
import type { AssetOfferDTO } from './assetOfferDTO';

export interface ProjectDTO {
  id: number;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  completed: boolean;
  medias: MediaDTO[];
  projectManager: UserInformationDTO;
  projectRoles: ProjectRoleDTO[];
  assetOffers: AssetOfferDTO[];
}
