/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectWithMatchingRolesListDTO } from './projectWithMatchingRolesListDTO';

export interface ProjectWithMatchingRolesListDTOAPIResponse {
  success?: boolean;
  data?: ProjectWithMatchingRolesListDTO;
  /** @nullable */
  error?: string | null;
}
