/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillType } from './skillType';

export interface ProjectRoleCreateDTO {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  cost: number;
  skillType: SkillType;
  remote: boolean;
}
