/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectDTO } from './projectDTO';

export interface ProjectWithMatchingRoleDTO {
  projectRoleId: number;
  project: ProjectDTO;
}
