/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { LocationDTO } from './locationDTO';
import type { MediaUpdateDTO } from './mediaUpdateDTO';
import type { ProjectRoleUpdateDTO } from './projectRoleUpdateDTO';

export interface ProjectUpdateDTO {
  id?: number;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  date: string;
  location: LocationDTO;
  medias: MediaUpdateDTO[];
  projectRoles: ProjectRoleUpdateDTO[];
}
