/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { RedeemVoucherCodeResponseDTO } from './redeemVoucherCodeResponseDTO';

export interface RedeemVoucherCodeResponseDTOAPIResponse {
  success?: boolean;
  data?: RedeemVoucherCodeResponseDTO;
  /** @nullable */
  error?: string | null;
}
