/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserInformationDTO } from './userInformationDTO';

export interface ReviewDTO {
  /** @minLength 1 */
  description: string;
  rating: number;
  createdAt: string;
  reviewerUser: UserInformationDTO;
}
