/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { User } from './user';

export interface Review {
  description?: string | null;
  id?: number;
  rating?: number;
  reviewedUser?: User;
  reviewedUserId?: number;
  reviewerUser?: User;
  reviewerUserId?: number;
}
