/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SeenMatchesDTO } from './seenMatchesDTO';

export interface SeenMatchesDTOAPIResponse {
  success?: boolean;
  data?: SeenMatchesDTO;
  /** @nullable */
  error?: string | null;
}
