/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillType } from './skillType';
import type { SkillGroupType } from './skillGroupType';

export interface SkillUpdateDTO {
  /** @nullable */
  id?: number | null;
  skillType: SkillType;
  skillGroupType: SkillGroupType;
  /** @nullable */
  description?: string | null;
  level?: number;
  /** @nullable */
  keywords?: string[] | null;
}
