/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillGroupType } from './skillGroupType';
import type { SkillType } from './skillType';
import type { User } from './user';

export interface Skill {
  description?: string | null;
  id?: number;
  level?: number;
  skillGroupType?: SkillGroupType;
  skillType?: SkillType;
  user?: User;
  userId?: number;
}
