/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillDTO } from './skillDTO';

export interface SkillDTOAPIResponse {
  success?: boolean;
  data?: SkillDTO;
  /** @nullable */
  error?: string | null;
}
