/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillType } from './skillType';
import type { SkillGroupType } from './skillGroupType';

export interface SkillDTO {
  id?: number;
  skillType?: SkillType;
  skillGroupType?: SkillGroupType;
  /** @nullable */
  description?: string | null;
  level?: number;
  /** @nullable */
  keywords?: string[] | null;
}
