/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SurveyAnswerDTO } from './surveyAnswerDTO';

export interface SurveyAnswerListDTO {
  /** @nullable */
  surveyAnswers?: SurveyAnswerDTO[] | null;
}
