/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface SurveyAnswerDTO {
  id?: number;
  userId?: number;
  surveyId?: number;
  questionId?: number;
  /** @nullable */
  answer?: string | null;
}
