/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SurveyAnswerListDTO } from './surveyAnswerListDTO';

export interface SurveyAnswerListDTOAPIResponse {
  success?: boolean;
  data?: SurveyAnswerListDTO;
  /** @nullable */
  error?: string | null;
}
