/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserProfileDetailsDTO } from './userProfileDetailsDTO';

export interface UserProfileDetailsDTOAPIResponse {
  success?: boolean;
  data?: UserProfileDetailsDTO;
  /** @nullable */
  error?: string | null;
}
