/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserLocationDTO } from './userLocationDTO';

export interface UserLocationDTOAPIResponse {
  success?: boolean;
  data?: UserLocationDTO;
  /** @nullable */
  error?: string | null;
}
