/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserPortofolioDTO } from './userPortofolioDTO';

export interface UserPortofolioDTOAPIResponse {
  success?: boolean;
  data?: UserPortofolioDTO;
  /** @nullable */
  error?: string | null;
}
