/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserLoginDTO {
  /** @minLength 1 */
  usernameOrEmail: string;
  /** @minLength 1 */
  password: string;
}
