/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { SkillUpdateDTO } from './skillUpdateDTO';

export interface UserUpdateDTO {
  /** @nullable */
  username?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  aboutYou?: string | null;
  /** @nullable */
  skills?: SkillUpdateDTO[] | null;
}
