/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserProfileDTO } from './userProfileDTO';

export interface UserProfilesDTO {
  userProfiles: UserProfileDTO[];
}
