/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ProjectInfoDTO } from './projectInfoDTO';

export interface UserLoginResponseDTO {
  /** @minLength 1 */
  username: string;
  userId: number;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  bannerPictureSrc: string;
  coins: number;
  projectsManaging: ProjectInfoDTO[];
}
