/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { LocationDTO } from './locationDTO';
import type { MediaCreateDTO } from './mediaCreateDTO';
import type { SkillUpdateDTO } from './skillUpdateDTO';
import type { MediaUpdateDTO } from './mediaUpdateDTO';

export interface UserUpdateDTO {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  aboutYou: string;
  location: LocationDTO;
  profilePicture: MediaCreateDTO;
  skills: SkillUpdateDTO[];
  portofolioMedias: MediaUpdateDTO[];
}
