/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserGetMatchingProjectRolesDTO {
  distance?: number;
  effort?: number;
}
