/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserDTO } from './userDTO';

export interface UserDTOAPIResponse {
  success?: boolean;
  data?: UserDTO;
  /** @nullable */
  error?: string | null;
}
