/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { LocationDTO } from './locationDTO';
import type { MediaDTO } from './mediaDTO';
import type { SkillDTO } from './skillDTO';

export interface UserProfileDetailsDTO {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  aboutYou: string;
  location: LocationDTO;
  profilePicture: MediaDTO;
  skills: SkillDTO[];
  portfolioMedias: MediaDTO[];
}
