/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserProfileDTO } from './userProfileDTO';

export interface UserProfileDTOAPIResponse {
  success?: boolean;
  data?: UserProfileDTO;
  /** @nullable */
  error?: string | null;
}
