/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { LocationDTO } from './locationDTO';
import type { MediaUpdateDTO } from './mediaUpdateDTO';
import type { SkillUpdateDTO } from './skillUpdateDTO';

export interface UserUpdateDTO {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  aboutYou: string;
  location: LocationDTO;
  profilePicture: MediaUpdateDTO;
  skills: SkillUpdateDTO[];
  portfolioMedias: MediaUpdateDTO[];
}
