/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserLocationUpdateDTO {
  longitude?: number;
  latitude?: number;
  /** @nullable */
  address?: string | null;
}
