/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { ReviewDTO } from './reviewDTO';
import type { SkillDTO } from './skillDTO';
import type { PortofolioContentDTO } from './portofolioContentDTO';
import type { ExperienceDTO } from './experienceDTO';

export interface UserProfileDTO {
  userId: number;
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  aboutYou: string;
  rating: number;
  totalReviews: number;
  reviewsReceived: ReviewDTO[];
  skills: SkillDTO[];
  portofolioContents: PortofolioContentDTO[];
  experiences: ExperienceDTO[];
}
