/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */
import type { UserProfilesDTO } from './userProfilesDTO';

export interface UserProfilesDTOAPIResponse {
  success?: boolean;
  data?: UserProfilesDTO;
  /** @nullable */
  error?: string | null;
}
