/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * CoCreateAPI
 * OpenAPI spec version: v1
 */

export interface UserInformationDTO {
  userId: number;
  /** @minLength 1 */
  username: string;
  /** @nullable */
  rating?: number | null;
  /** @nullable */
  publicKey?: string | null;
}
